# Generated by Django 3.2.13 on 2022-06-13 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("reacted_by", "to_post")},
        ),
    ]
